config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: [:new, :create] do
    get :logout, on: :collection
  end
  resources :text_templates do
    get :preview, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :text_template
  belongs_to :recipient
end

app/models/text_template.rb
class TextTemplate < ActiveRecord::Base
  belongs_to :user
  has_many :texts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :recipients
  has_many :text_templates

  validates_presence_of :email, :phone_number
  validates :email, uniqueness: true
  validates :phone_number, uniqueness: true
  validates :username, uniqueness: true 
  validates :password, length: {minimum: 6}, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  
  private
  
  def current_user
    @current_user ||= User.find_by(email: session[:email])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    debugger
    @user = User.find_by(email: params[:user][:email])
    if @user&.authenticate(params[:user][:password])
      session[:email] = @user.email
      redirect_to new_text_templat_path
    else
      @user = User.new
      flash[:error] = "Incorrect email or password"
      render :new and return
    end
  end

  def destroy
    current_user.currently_logged_in = false
    current_user.save
    session[:email] = nil
    redirect_to :new and return
  end

end

app/controllers/text_templates_controller.rb
class TextTemplatesController < ApplicationController

  def index
    @text_templates = current_user.text_templates
  end

  def new
  end

  def preview
    @text_template = current_user.text_templates.new

    @text_template.body = params[:text_template][:body]
    @text_template.send_at = params[:text_template][:send_at] + " EST"
  end

  def create
  end

  def destroy
  end

  private

  def text_template_params
    params.require(:text_template).permit(:body, :send_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="header">
  <div class="user-info">
    <div class="user-circle">
      <%= @current_user.username.first.upcase %>
    </div>
    <div class="username">
      <%= @current_user.username %>
    </div>
    <a class="logout btn" href="<%= logout_sessions_path %>">Log Out</a>
  </div>
  <div class="app-name">
    <i class="fas fa-chalkboard-teacher"></i>
    <div class="text">TeacherTexter</div>
    <i class="fas fa-sms"></i></div>
  <div class="links">
    <a href="<%= new_text_template_path %>" class="header-btn btn">New Text</a>
    <a href="<%= text_templates_path %>" class="header-btn btn">Saved Texts</a>
    <a href="<%= %>%" class="header-btn btn">Recipients</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherTexter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/3ba9c7c7eb.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker-standalone.css" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "header" if @current_user %>
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
</script>

app/views/text_templates/_text_template.html.erb
<div>
  <%= template.created_at %>
</div>

app/views/text_templates/index.html.erb
<div class="page-container">
  <div class="text-templates">
    <% @text_templates.each do |template| %>
      <%= render text_template, template: template %>
    <% end%>
  </div>
</div>

app/views/text_templates/new.html.erb
<div class="new-template">
  <form class="form-horizontal" action="<%= preview_text_templates_path %>" method="GET" >
    <div class="form-group">
        <label for="text_template_body" class="control-label">Text Body</label>
        <textarea class="body form-control" rows="8" type="text" name="text_template[body]" id="text_template_body" style="margin: 0px; width: 528px; height: 286px;"></textarea>
    </div>
    <div class='form-group date'>
      <label for="text_template_send_at" class="control-label">Send At</label>
      <div class="input-group" id='datetimepicker1'>
        <input type='text' id="text_template_send_at" name="text_template[send_at]" class="form-control" />
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-default">Preview</button>
    </div>

  </form>
</div>
 